apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: self-service-template
  title: Add extra services into OpenShift Namespace
  description: Add Kafka, PostgreSQL and ResourceQuota to the namespace
  tags:
    - recommended
    - kafka
    - postgresql
    - quotas
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for required Services
      required:
        - namespace
      properties:
        enable_kafka:
          title: Install Kafka Broker
          type: boolean
          description: Install Kafka Cluster in the namespace
          default: true
        enable_postgres:
          title: Enable PostgreSQL Database
          type: boolean
          default: false
          description: Install PosgreSQL Database in the namespace
        cpu_limit:
          title: Required CPU
          type: number
          default: 2
          description: CPU Required for your namespace (1-4)
        memory_limit:
          title: Memory Limit
          type: number
          default: 2
          description: Memory required for your namespace (1-8)   
        namespace:
          title: Namespace
          type: string
          default: quarkus-app-dev
          maxLength: 28
          description: Namespace where you want to apply this template

    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-9hhkz.sandbox2009.opentlc.com
              enum:
                - gitlab-gitlab.apps.cluster-9hhkz.sandbox2009.opentlc.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development

  steps:
  
    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          namespace: ${{ parameters.namespace }}
          destination: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.namespace}}-self-service.git
          git_owner: ${{ parameters.repo.owner }}
          cluster: .apps.cluster-9hhkz.sandbox2009.opentlc.com
          namespace: ${{ parameters.namespace }}-dev
          repository_host: ${{ parameters.repo.host }}
          user: ${{ user.entity.metadata.name }}
        targetPath: ./tenant-gitops

    - id: publish-gitops
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.namespace}}-self-service"
        title: gitops resources for ${{ parameters.namespace }}
        description: gitops resources for ${{ parameters.namespace }}
        sourcePath: ./tenant-gitops
        repoVisibility: public

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.namespace }}-self-service
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.namespace }}-self-service.git
        path: 'argocd/'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish-gitops.output.remoteUrl }}