apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: self-service-template
  title: Quarkus Service with ArgoCD and a Tekton Pipeline
  description: Create a simple microservice using Quarkus with ArgoCD and a Tekton Pipeline
  tags:
    - recommended
    - kafka
    - postgresql
    - quotas
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for required Services
      required:
        - namespace
      properties:
        enable_kafka:
          title: Install Kafka Broker
          type: boolean
          description: Install Kafka Cluster in the namespace
          default: true
        enable_postgres:
          title: Enable PostgreSQL Database
          type: boolean
          default: false
          description: Install PosgreSQL Database in the namespace
        cpu_limit:
          title: Required CPU
          type: number
          default: 2
          description: CPU Required for your namespace (1-4)
        memory_limit:
          title: Memory Limit
          type: number
          default: 2
          description: Memory required for your namespace (1-8)   
        namespace:
          title: Namespace
          type: string
          default: quarkus-app-dev
          maxLength: 14
          description: Namespace where you want to deploy this template

    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-9hhkz.sandbox2009.opentlc.com
              enum:
                - gitlab-gitlab.apps.cluster-9hhkz.sandbox2009.opentlc.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          namespace: ${{ parameters.namespace }}
          memory_limit: ${{ parameters.memory_limit }}
          cpu_limit: ${{ parameters.cpu_limit }}
          enable_postgres: ${{ parameters.enable_postgres }}
          enable_kafka: ${{ parameters.enable_kafka }}
          owner: ${{ user.entity.metadata.name }}
          cluster: .apps.cluster-9hhkz.sandbox2009.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.component_id }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}-gitops.git
          source_repository: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}.git
          repository_name: ${{parameters.component_id}}
          git_owner: ${{ parameters.repo.owner }}
          cluster: .apps.cluster-9hhkz.sandbox2009.opentlc.com
          namespace: ${{ parameters.component_id }}-dev
          image_registry: ${{ parameters.image_registry }}
          image_host: ${{ parameters.image_host }}
          image_organization: ${{ parameters.image_organization }}
          image_name: ${{ parameters.component_id }}
          image_tag: ${{ parameters.image_tag }}
          port: 8080
          repository_host: ${{ parameters.repo.host }}
          deployment_name: quarkus-template
          user: ${{ user.entity.metadata.name }}
        targetPath: ./tenant-gitops

    - id: publish-gitops
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}-gitops"
        title: gitops resources for ${{ parameters.component_id }}
        description: gitops resources for ${{ parameters.component_id }}
        sourcePath: ./tenant-gitops
        repoVisibility: public

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.component_id }}-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.component_id }}-gitops.git
        path: 'argocd/'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
