---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.namespace }}-self-service
  namespace: janus-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: janus
  source:
    repoURL: ${{ values.destination }}
    targetRevision: HEAD
    path: ./helm/app
    helm:
      parameters:
      - name: namespace.name
        value: ${{ values.namespace }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true
