---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: {{ $.Values.cpu }}
    requests.memory: {{ $.Values.memory}}Gi
    limits.cpu:  {{ $.Values.cpu }}
    limits.memory: {{ $.Values.memory}}Gi